id_column: "$submission_id"
title_column: "Title of the workshop"
form_column: "form_link"
description_column: "A short description of your workshop (max 250 words)"
outcome_column: "A brief statement on the learning outcomes from the workshop, to be used on the website for the event."
pre_requisite_column: "What are the prerequisites for attending the workshop?"
instructor_column: "Your name (first name and surname)?"
email_column: "What is your e-mail address?"
duration_column: "Length of the workshop (e.g., 2 hours, half a day or a whole day)"
material_column: "Please indicate what you expect your audience need to bring to the workshop"
target_column: "What is the target audience for your workshop?"
