date_column: "Date"
time_column: "Time"
title_column: "Workshop name"
id_column: "Number"
nettskjema_id_column: "Nettskjema ID"
room_column: "Room in Ole Johan Dalshus"
main_instructor_column: "Instructor 1"
helper_instructor_column: "Instructor 2"
max_attendance: "Max capacity"
duration_column: "Length"
start_time_column: "Start time"
end_time_column: "End time"
networking_event_column: "Networking event"
status_column: "Instructor: confirm time"